---
- hosts: all
  become: yes
  tasks:
  - name: Install EPEL Repo package from standart repo
    yum:
      name: epel-release
      state: present
  - name: install softs on CentOS
    yum:
      name:
      - wget
      - httpd
      - tftp-server
      - dhcp-server
    state: present
    update_cache: true
  - name: Download ISO image CentOS 8.4.2105
    get_url:
      url: https://mirror.sale-dedic.com/centos/8.4.2105/isos/x86_64/CentOS-8.4.2105-x86_64-dvd1.iso
      dest: /root/CentOS-8.4.2105-x86_64-dvd1.iso
      mode: '0755'
  - name: Create ISO directory
    file:
      path: /iso
      state: directory
      mode: '0755'
  - name: Mount ISO image
    mount:
      path: /mnt
      src: /root/CentOS-8.4.2105-x86_64-dvd1.iso
      fstype: iso9660
      opts: ro,loop
      state: mounted
  - name: copy ALL files from /mnt to /iso
    copy:
      src: /mnt/
      dest: /iso
      remote_src: yes
      directory_mode: yes
  - name: set up httpd config
    template:
      src: pxeboot.conf
      dest: /etc/httpd/conf.d/pxeboot.conf
      owner: root
      group: root
      mode: 0640
  - name: restart httpd
    service:
      name: httpd
      state: restarte